server:
  servlet:
    context-path: /anagrafica

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anagrafica_radiologica
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.anagrafica.radiologica: INFO
    org.hibernate.SQL: WARN
